### ISSUE TITLE
执行出错

### ISSUE THREAD

**Issue by moli721** [alex-away/cursor-machine-id#1]
配置了执行策略依然出错，如图：
![cursor](https://github.com/user-attachments/assets/07f37a8c-57a4-4358-81e5-b8d15304b65b)

**Comment by moli721** [comment]
已解决，问了gpt之后给出的答案，需要解除锁定：
确保脚本没有被锁定： 有时候，下载的脚本可能会被 Windows 安全策略标记为“来自 Internet 的文件”，需要解锁。右键点击脚本文件，选择“属性”，然后查看是否有“解除锁定”按钮，点击它来解锁文件。

**Comment by alex-away** [comment]
did [this](https://github.com/alex-away/cursor-machine-id?tab=readme-ov-file#execution-policy) solve your issue?

**Comment by moli721** [comment]
> did [this](https://github.com/alex-away/cursor-machine-id?tab=readme-ov-file#execution-policy) solve your issue?

It was resolved by asking GPT. The solution was to **unlock the script**: Sometimes, downloaded scripts are marked as "from the Internet" by Windows security policies, and need to be unlocked. Right-click the script file, select "Properties," then check for a "Unblock" button and click it to unlock the file.

Yes, it's just because the script was locked, marked as "from the Internet" by Windows security policies, and needed to be unlocked.

**Comment by alex-away** [comment]
oh ok, thanks for the translation!
and I've updated the [README.md](https://github.com/alex-away/cursor-machine-id?tab=readme-ov-file#execution-policy) too
